# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: http://cangin.top
date_format: "ordinal"
title: 凔音/Cangin
subtitle: "你们要谨慎行事，不要像愚昧人，当像智慧人。要爱惜光阴，因为现今的世代邪恶。（以弗所书5:15-16）"
#subtitle: "Cangin's Personal Blog"
description: "Record ideas and knowledge"
keywords: Algorithm,Machine Learning(eg.Deep Learning),Data mining
timezone: Asia/Beijing
encoding: "utf-8"
#显示git仓库的数量
side_bar_repo_limit: 1

# ---------------- #
#      Author      #
# ---------------- #
author: Cangin
organization: FINAL
organization_url: http://cangin.top
github_username: fei5156
location: BeiJing
email: fei51568@gmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: Home


  -
    href: /categories/
    label: Blog
   


  -
    href: /open-source/
    label: Open-source
   

  -
    href: /wiki/
    label: Wiki

  -
    href: /links/
    label: Link

  -
    href: /about/
    label: About

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: fei5156/fei5156.github.io

# ---------------- # 
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
#comments_provider: gitalk
#comments_provider: gitalk


# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
#disqus:
#    username: wenjun d

    
# https://imsun.net/posts/gitment-introduction/
#gitment:
#    owner: DWJWendy
#    repo: blog-comments
#    oauth:
#        client_id: ef4ee0f3d879e724a46c
#        client_secret: 2a98b4739a3712bb347ed63cf50b5a07e41f4c48
# https://github.com/gitalk/gitalk#install
#gitalk:
#    owner: DWJWendy
#    repo: blog-comments
#    clientID: ef4ee0f3d879e724a46c
#    clientSecret: 2a98b4739a3712bb347ed63cf50b5a07e41f4c48
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-80669434-1

# ---------------- #
#    Counter     #
# ---------------- #
#使用的是learncloud，appid和key更换成自己的
#leancloud:
#  enable: true
#  app_id: EfLTUbK2fJ0dYLAq609NQ2k4-gzGzoHsz
#  app_key: 5Agxeshbunhh9y6XQftwEvGj
